### PR TITLE
Framework target

### PR DESCRIPTION
**Pull request by akolov**
Added Framework target which can be used on OS X and iOS 8

### CODE REVIEW

**Comment by tocker** [comment]
Hi @akolov,
Thanks for the PR!
We are reviewing framework requirements and will consider merging your code.

**Comment by zenangst** [comment]
@tocker bump! :sunglasses:

**Comment by krodak** [comment]
@tocker bump! :+1:

**Comment by itinance** [comment]
+ @akolov
+ @tocker

**Comment by timbroder** [comment]
@tocker Is there anything preventing this from being merged in?

**Comment by antigp** [comment]
+1 
It's add Carthage support #47

**Comment by nitzanj** [comment]
We're currently in the process of restructuring this repository to both facilitate support for frameworks other than iOS and add Carthage and Swift-Package-Manager support. Closing.

**Pull request closed without merging**
